version: 1
title: Initialize plugin skeleton
acceptance:
- main plugin file and loader present
- composer.json, phpcs.xml, phpunit.xml added
- assets/, includes/, languages/ directories
files:
- "news-listing/news-listing.php"
- "news-listing/includes/Shortcode.php"
- "news-listing/assets/css/news-listing.css"
- "news-listing/assets/js/news-listing.js"
- "readme.txt"
- "composer.json"
- "phpcs.xml"
- "phpunit.xml"


- id: T-010
milestone: M1
title: Shortcode registration & attribute validation
acceptance:
- defaults: layout=grid, count=9, category_icon=true, tags_badges=true
- sanitize all attrs; boolean casting; invalid values fall back to defaults


- id: T-020
milestone: M1
title: Query builder for categories & count
acceptance:
- category slugs parsed (comma-separated); query returns posts in any listed category
- unit tests cover slug parsing and count limits


- id: T-030
milestone: M2
title: Grid renderer with pagination
acceptance:
- responsive grid with thumbnail, title, excerpt, icons placeholder
- paginate_links() renders beneath grid; works on static front page and archives


- id: T-040
milestone: M3
title: Carousel renderer + JS controls
acceptance:
- horizontal scroll-snap container; previous/next buttons; keyboard and touch support
- no external libraries; no jQuery dependency


- id: T-050
milestone: M4
title: Category icons via ACF (soft dep)
acceptance:
- attempts `get_field('category_icon', 'category_'+term_id)` if ACF exists; else tries `get_term_meta(term_id, 'category_icon', true)`; else omit
- images sanitized; alt = category name


- id: T-060
milestone: M4
title: Tags as thumbnail badges
acceptance:
- up to 3 tags; overlay top of thumbnail; truncation with ellipsis; accessible labels


- id: T-070
milestone: M4
title: Styling & 3:2 thumbnails
acceptance:
- CSS ensures 3:2 with aspect-ratio + fallback; lazy loading; srcset
- namespaced classes `nlp-*`; enqueued only when shortcode present


- id: T-080
milestone: M5
title: Accessibility & i18n
acceptance:
- arrow buttons and pagination have aria-labels; focus visible
- .pot generated; text domain `news-listing`


- id: T-090
milestone: M5
title: Docs, PHPCS, tests
acceptance:
- README: usage, params table, examples
- PHPCS clean; basic unit tests pass

milestones:
  - id: M6
    name: v1.0.1 Polish & Fixes
    exit:
      - all T-11x acceptance checks pass
      - before/after screenshots attached in the PR
      - PHPCS clean; no console errors on preview

tasks:
  - id: T-110
    milestone: M6
    title: Simplify carousel arrows and color
    type: enhancement
    acceptance:
      - Carousel left/right buttons display literal "<" and ">".
      - Arrow color is exactly #333333; focus outline remains visible.
      - Buttons remain ≥36×36 px hit area; have aria-labels.
      - Don't use <button> tags for arrows, use <div> instead.
      - use svg for the arrows.
      - use font-size: 48px;
    files:
      - "news-listing/assets/css/news-listing.css"
      - "news-listing/assets/js/news-listing.js"

  - id: T-111
    milestone: M6
    title: Carousel step equals `visible_posts` with sliding animation
    type: enhancement
    acceptance:
      - add another parameter to the shortcode <visible_posts> to set the number of posts to display in the carousel.
      - Clicking arrows or pressing Left/Right scrolls by exactly `<visible_posts>` cards (card width + current inter-card gap).
      - For carousel layout, <visible_posts> is the number of posts to display in the carousel.
      - Smooth sliding animation (~250–400ms) using vanilla JS (requestAnimationFrame or smooth scroll) — no jQuery.
      - Works when remaining items < count (stops at ends gracefully; no overscroll).
      - Wrapper exposes `data-count="<visible_posts>"` so JS can determine step size; keyboard matches click behavior.
    files:
      - "news-listing/includes/Shortcode.php"   # add data-count to wrapper
      - "news-listing/assets/js/news-listing.js"
      - "news-listing/assets/css/news-listing.css"

  - id: T-112
    milestone: M6
    title: Fix grid pagination layout and arrow styles
    type: bug
    acceptance:
      - Pagination list items render horizontally (inline/inline-flex), not stacked vertically.
      - Prev/Next show as "<" and ">" and have no border box; numbered pages keep minimal styling.
      - `aria-label` present on the nav wrapper; focusable controls show visible focus outline.
      - Verified on static pages and archives.
    files:
      - "news-listing/assets/css/news-listing.css"
      - "news-listing/includes/Shortcode.php"

  - id: T-113
    milestone: M6
    title: Overlay category icons on thumbnail (bottom-right horizontal stack)
    type: enhancement
    acceptance:
      - Category icons render inside the thumbnail, bottom-right corner, stacked horizontally with 6–8px gap.
      - No layout shift when icons load; appear above the image (proper z-index) and do not obscure tag badges.
      - `alt` equals category name; if no icon, omit cleanly (no empty container).
      - Works with 1–4 icons.
    files:
      - "news-listing/includes/Shortcode.php"   # move icons markup into thumbnail container
      - "news-listing/assets/css/news-listing.css"

  - id: T-114
    milestone: M6
    title: Increase grid/item gaps to 32px (and align carousel gap)
    type: enhancement
    acceptance:
      - Grid gutter between items is exactly 32px at all breakpoints.
      - Carousel inter-card gap is 32px; T-111 step calculation uses card width + 32px.
      - Visual check confirms consistent spacing across grid and carousel.
    files:
      - "news-listing/assets/css/news-listing.css"
      - "news-listing/assets/js/news-listing.js"
